/******** user login **************/
###

GET http://localhost:3001/api/login
###
post http://localhost:3001/api/login http/1.1
Content-Type: application/json

{ 
"userName": "ali", 
"password": "ali"
}
###
/************ End user login ***************/
/************* Blogs begin****** ***********/
###
post http://localhost:3001/api/blogs http/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImhlbGVuIiwidXNlcklkIjoiNjJhODc0ZmM1ODdiM2Q2YTYwNzdlOGExIiwiaWF0IjoxNjU2NTE4OTUyLCJleHAiOjE2NTY1MTkzMTJ9.mUMS5anVjATT3brHRxOK49FVGt2nbnLEhARqh-oB_bE

{
"title": "The Dry Weather", 
"author": "no one", 
"url": "www.dry.com", 
"likes":98
}
###
GET http://localhost:3001/api/blogs HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImhlbGVuIiwidXNlcklkIjoiNjJhODc0ZmM1ODdiM2Q2YTYwNzdlOGExIiwiaWF0IjoxNjU2NTE4OTUyLCJleHAiOjE2NTY1MTkzMTJ9.mUMS5anVjATT3brHRxOK49FVGt2nbnLEhARqh-oB_bE
###
GET http://localhost:3001/api/blogs/62a8d842587b3d6a6077e8ba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImhlbGVuIiwidXNlcklkIjoiNjJhODc0ZmM1ODdiM2Q2YTYwNzdlOGExIiwiaWF0IjoxNjU2NTE4OTUyLCJleHAiOjE2NTY1MTkzMTJ9.mUMS5anVjATT3brHRxOK49FVGt2nbnLEhARqh-oB_bE
###
delete http://localhost:3001/api/blogs/62a8d842587b3d6a6077e8ba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImhlbGVuIiwidXNlcklkIjoiNjJhODc0ZmM1ODdiM2Q2YTYwNzdlOGExIiwiaWF0IjoxNjU2NTE4OTUyLCJleHAiOjE2NTY1MTkzMTJ9.mUMS5anVjATT3brHRxOK49FVGt2nbnLEhARqh-oB_bE
###
PUT http://localhost:3001/api/blogs/62a8d842587b3d6a6077e8ba
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImhlbGVuIiwidXNlcklkIjoiNjJhODc0ZmM1ODdiM2Q2YTYwNzdlOGExIiwiaWF0IjoxNjU2NTE4OTUyLCJleHAiOjE2NTY1MTkzMTJ9.mUMS5anVjATT3brHRxOK49FVGt2nbnLEhARqh-oB_bE

{
"title": "how to buy girrafe03",
"author": "magdooniata03", 
"url": "www.com03", 
"likes":3
}
###
PATCH  http://localhost:3001/api/blogs/62a8d842587b3d6a6077e8ba
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImhlbGVuIiwidXNlcklkIjoiNjJhODc0ZmM1ODdiM2Q2YTYwNzdlOGExIiwiaWF0IjoxNjU2NTE4OTUyLCJleHAiOjE2NTY1MTkzMTJ9.mUMS5anVjATT3brHRxOK49FVGt2nbnLEhARqh-oB_bE

{
"likes":30
}

###
GET http://localhost:3001/api/users HTTP/1.1

helen: e yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImhlbGVuIiwidXNlcklkIjoiNjJhODc0ZmM1ODdiM2Q2YTYwNzdlOGExIiwiaWF0IjoxNjU1MzYzNTE2LCJleHAiOjE2NTUzNjcxMTZ9.SOlNDFUq_EQfQiZFnKvGywPGlEbR72zqzvOOAEJXIgY
ali: e yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImFsaSIsInVzZXJJZCI6IjYyYTg3NTFjNTg3YjNkNmE2MDc3ZThhNyIsImlhdCI6MTY1NTM2MzIwNSwiZXhwIjoxNjU1MzY2ODA1fQ.kcjnSA8tXhgYhpIk3XTlaFwnQ5MD50gqDXODLbtp6fc

###
post http://localhost:3001/api/testing/reset
