put http://localhost:3001/api/persons/628226a7bf742a859c8200c9
content-type: application/json

{
  "name": "Patrick",
  "number": "9999999"
}
###
put http://localhost:3001/api/persons/2
content-type: application/json

{
  "name": "patrishia",
  "number": "000"
}
###
put http://localhost:3001/api/persons/6281dcfb2c0076f252ecb9d7
content-type: application/json

###
put http://localhost:3001/api/persons/6281dcfb2c0076f252ecb9d7
content-type: application/json

{
  "name": "cerna jose"
}
###
get http://localhost:3001/api/persons